#!/bin/bash

#-------------------------------------------------#
#  Clean the directory when the work is finished  #
#-------------------------------------------------#

# Stuff creaed by autotools
rm -fR NEWS README AUTHORS ChangeLog
rm -fR COPYING depcomp INSTALL install-sh missing
rm -fR aclocal.m4 autom4te.cache/ config.log config.status configure

# Stuff left by Fortran compilation
rm -fR Makefile.in */Makefile.in */*/Makefile.in */*/*/Makefile.in */*/*/*/Makefile.in
rm -fR Makefile */Makefile */*/Makefile */*/*/Makefile */*/*/*/Makefile
rm -fR *.real */*.real */*/*.real */*/*/*.real */*/*/*/*.real
rm -fR *.o */*.o */*/*.o */*/*/*.o */*/*/*/*.o
rm -fR Modules/*.mod
rm -fR Process/Communication/*.f90
rm -fR Divide/Divide
rm -fR Generate/Generate
rm -fR Neu2TFlowS/Neu2TFlowS
rm -fR Process/Process
rm -fR Utilities/.deps
